version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    container_name: php-container

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network
    container_name: nginx-container

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: stumanager
    networks:
      - app-network
    container_name: mysql-container

volumes:
  mysql-data:


networks:
  app-network:
    driver: bridge